version: '3.8'
services:
  backend:
    container_name: ayaz-memster-backend
    restart: always
    image: ghcr.io/ayaz-memster/backend:${IMAGE_VERSION}
    pull_policy: always
    ports:
      - 3000:3000
    labels:
      - traefik.http.routers.ayaz-memster-backend.rule=Host(`ayaz-memster.okinazuno.me`) && PathPrefix(`/api`)
      - traefik.http.routers.ayaz-memster-backend.tls=true
      - traefik.http.routers.ayaz-memster-backend.tls.certresolver=letsEncrypt
      - traefik.http.services.ayaz-memster-backend.loadbalancer.server.port=3000
      - traefik.http.middlewares.ayaz-memster-backend.ratelimit.average=100
      - traefik.http.middlewares.ayaz-memster-backend.ratelimit.burst=50
    environment:
      - DB_URL=${DB_URL}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production

networks:
  default:
    external: true
    name: traefik-network
